### ISSUE TITLE
Commits are staging even though wrong commit message is provided

### ISSUE THREAD

**Issue by krishna63** [kentcdodds/validate-commit-msg#75]
Hi Team,
I have forked this [project | https://github.com/kentcdodds/validate-commit-msg.git] and trying to understand how it works, so made small modifications like adding empty line in package.json and executed the following code in the git GUI

git commit -am "testing purpose" 
 Expectation: I am expecting an error to appear saying that "Please fix your commit message"and stop the the commit to staging

Actual : I see that commit's are staging PFA screenshot

![image](https://cloud.githubusercontent.com/assets/5499820/25366495/a6453936-298d-11e7-9f77-4ee48f000c50.png)

Please help me out

**Comment by kentcdodds** [comment]
It's because our commit hook is [set to](https://github.com/kentcdodds/validate-commit-msg/blob/e3a81f8298427b94be01e7ea305505ee6005cec8/package.json#L10):

```
opt --in commitmsg --exec "node ./lib/cli.js"
```

This is using [opt-cli](https://www.npmjs.com/package/opt-cli) so new users contributing to the project don't have the scripts run, meaning the barrier to contributing is lowered. If you want to opt-into the git hooks, then create a file in the root directory called `.opt-in` and add:

```
commitmsg
precommit
```

See [the contributing guidelines](https://github.com/kentcdodds/validate-commit-msg/blob/master/CONTRIBUTING.md) for more info on contributing. Thanks!
